import 'job.dart';

List<Job> getMockJobs() {
  return [
    Job(
      id: "1",
      title: "Software Engineer",
      company: "Tech Corp",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 70,000 - RM 100,000",
      description:
          "Responsible for developing and maintaining software applications.",
      skillsRequired: ["Flutter", "Dart", "Firebase"],
      employeeReview: "Innovative environment, supportive team.",
    ),
    // ... Add more mock Job instances hereJob(
    Job(
      id: "2",
      title: "Data Analyst",
      company: "Data Insights",
      location: "New York, NY",
      salaryRange: "\$70,000 - \$90,000",
      description: "Analyze data trends and provide insights.",
      skillsRequired: ["Python", "SQL", "Tableau"],
      employeeReview: "Supportive management and growth opportunities.",
    ),
    Job(
      id: "3",
      title: "Graphic Designer",
      company: "Creative Studio",
      location: "Kuala Lumpur",
      salaryRange: "RM 50,000 - RM 70,000",
      description: "Design engaging graphics for various media.",
      skillsRequired: ["Adobe Photoshop", "Illustrator", "InDesign"],
      employeeReview: "Innovative environment with creative freedom.",
    ),
    Job(
      id: "4",
      title: "Marketing Manager",
      company: "Bright Marketing",
      location: "Penang",
      salaryRange: "RM 80,000 - RM 100,000",
      description: "Lead marketing strategies and campaigns.",
      skillsRequired: ["Digital Marketing", "SEO", "Leadership"],
      employeeReview: "Dynamic team with great career progression.",
    ),
    Job(
      id: "5",
      title: "Civil Engineer",
      company: "BuildCon Engineering",
      location: "Johor Bahru",
      salaryRange: "RM 70,000 - RM 90,000",
      description: "Oversee construction projects and ensure compliance.",
      skillsRequired: ["AutoCAD", "Project Management", "Analytical Skills"],
      employeeReview: "Challenging projects with supportive colleagues.",
    ),
    Job(
      id: "6",
      title: "HR Specialist",
      company: "People First HR",
      location: "Kuala Lumpur",
      salaryRange: "RM 60,000 - RM 80,000",
      description: "Manage HR functions and employee relations.",
      skillsRequired: ["Recruiting", "HR Policies", "Communication"],
      employeeReview: "Great work culture and learning opportunities.",
    ),
    Job(
      id: "7",
      title: "IT Support Technician",
      company: "Tech Solutions",
      location: "Melaka",
      salaryRange: "RM 40,000 - RM 60,000",
      description: "Provide technical support and troubleshoot IT issues.",
      skillsRequired: ["Technical Support", "Networks", "Problem Solving"],
      employeeReview: "Supportive team with a strong focus on training.",
    ),
    Job(
      id: "8",
      title: "Business Analyst",
      company: "Insight Analytics",
      location: "Selangor",
      salaryRange: "RM 70,000 - RM 90,000",
      description: "Analyze business trends and provide strategic insights.",
      skillsRequired: ["Data Analysis", "SQL", "Business Acumen"],
      employeeReview: "Collaborative environment with growth potential.",
    ),
    Job(
      id: "9",
      title: "Restaurant Manager",
      company: "Gourmet Bistro",
      location: "Ipoh",
      salaryRange: "RM 50,000 - RM 70,000",
      description: "Manage restaurant operations and staff.",
      skillsRequired: ["Customer Service", "Management", "Food Safety"],
      employeeReview: "Fast-paced environment with a focus on quality.",
    ),
    Job(
      id: "10",
      title: "Accountant",
      company: "Prime Accounting",
      location: "Kota Kinabalu",
      salaryRange: "RM 60,000 - RM 80,000",
      description: "Manage financial records and auditing processes.",
      skillsRequired: ["Accounting", "Tax Knowledge", "Attention to Detail"],
      employeeReview: "Professional team with a focus on accuracy.",
    ),
    Job(
      id: "11",
      title: "Sales Executive",
      company: "Dynamic Sales Co.",
      location: "Kuching",
      salaryRange: "RM 45,000 - RM 65,000",
      description: "Drive sales growth and develop client relationships.",
      skillsRequired: ["Sales", "Negotiation", "Communication"],
      employeeReview: "Competitive environment with high earning potential.",
    ),
    Job(
      id: "12",
      title: "Web Developer",
      company: "Innovative Web Solutions",
      location: "Petaling Jaya",
      salaryRange: "RM 55,000 - RM 75,000",
      description: "Develop and maintain websites and web applications.",
      skillsRequired: ["HTML", "CSS", "JavaScript"],
      employeeReview:
          "Creative team and opportunities to work on diverse projects.",
    ),
    Job(
      id: "13",
      title: "Data Scientist",
      company: "Insightful Analytics",
      location: "Singapore",
      salaryRange: "SGD 80,000 - SGD 120,000",
      description:
          "Utilize data to uncover insights and make data-driven decisions.",
      skillsRequired: ["Machine Learning", "Python", "Statistics"],
      employeeReview: "Cutting-edge projects and supportive team environment.",
    ),
    Job(
      id: "14",
      title: "Cybersecurity Analyst",
      company: "SecureTech Solutions",
      location: "San Francisco, CA",
      salaryRange: "\$90,000 - \$110,000",
      description: "Protect company networks and systems from cyber threats.",
      skillsRequired: [
        "Cybersecurity",
        "Network Security",
        "Penetration Testing"
      ],
      employeeReview:
          "Exciting challenges and opportunities for professional growth.",
    ),
    Job(
      id: "15",
      title: "Systems Administrator",
      company: "Cloud Innovations",
      location: "Seattle, WA",
      salaryRange: "\$75,000 - \$95,000",
      description: "Manage and maintain organization's IT infrastructure.",
      skillsRequired: [
        "System Administration",
        "Network Administration",
        "Linux"
      ],
      employeeReview:
          "Dynamic work environment with opportunities for skill development.",
    ),
    Job(
      id: "16",
      title: "Machine Learning Engineer",
      company: "AI Dynamics",
      location: "London, UK",
      salaryRange: "£60,000 - £90,000",
      description:
          "Design and implement machine learning models and algorithms.",
      skillsRequired: ["Machine Learning", "Python", "Deep Learning"],
      employeeReview: "Innovative projects and supportive colleagues.",
    ),
    Job(
      id: "17",
      title: "DevOps Engineer",
      company: "Agile DevOps Solutions",
      location: "Berlin, Germany",
      salaryRange: "€70,000 - €100,000",
      description: "Streamline software development and deployment processes.",
      skillsRequired: ["DevOps", "CI/CD", "Cloud Computing"],
      employeeReview:
          "Collaborative culture with a focus on continuous improvement.",
    ),
    Job(
      id: "18",
      title: "UI/UX Designer",
      company: "Interactive Designs",
      location: "Toronto, Canada",
      salaryRange: "CAD 70,000 - CAD 90,000",
      description: "Create intuitive and visually appealing user interfaces.",
      skillsRequired: ["UI/UX Design", "Prototyping", "User Research"],
      employeeReview:
          "Creative atmosphere with opportunities for design innovation.",
    ),
    Job(
      id: "19",
      title: "Network Engineer",
      company: "Connectivity Solutions",
      location: "Sydney, Australia",
      salaryRange: "AUD 80,000 - AUD 110,000",
      description: "Design, implement, and manage computer networks.",
      skillsRequired: ["Network Engineering", "Cisco", "Routing and Switching"],
      employeeReview: "Exciting projects and a supportive team environment.",
    ),
    Job(
      id: "20",
      title: "Full Stack Developer",
      company: "CodeCrafters Inc.",
      location: "Austin, TX",
      salaryRange: "\$85,000 - \$110,000",
      description: "Develop both client-side and server-side software.",
      skillsRequired: ["JavaScript", "Node.js", "React", "MongoDB"],
      employeeReview:
          "Innovative projects and opportunities for skill advancement.",
    ),
    Job(
      id: "21",
      title: "AI Research Scientist",
      company: "FutureTech AI",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 90,000 - RM 120,000",
      description:
          "Conduct research on artificial intelligence and machine learning.",
      skillsRequired: ["Machine Learning", "Python", "Deep Learning"],
      employeeReview: "Challenging projects with cutting-edge technology.",
    ),
    Job(
      id: "22",
      title: "Blockchain Developer",
      company: "Crypto Innovations",
      location: "Penang, Malaysia",
      salaryRange: "RM 80,000 - RM 110,000",
      description: "Develop and maintain blockchain-based applications.",
      skillsRequired: ["Blockchain", "Smart Contracts", "Solidity"],
      employeeReview: "Innovative projects and a dynamic team.",
    ),
    Job(
      id: "23",
      title: "Cloud Solutions Architect",
      company: "Cloud Masters",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 100,000 - RM 130,000",
      description: "Design and implement cloud-based solutions.",
      skillsRequired: ["AWS", "Azure", "Cloud Architecture"],
      employeeReview: "Great opportunities for career advancement.",
    ),
    Job(
      id: "24",
      title: "Cybersecurity Specialist",
      company: "SecureTech Solutions",
      location: "Johor Bahru, Malaysia",
      salaryRange: "RM 90,000 - RM 120,000",
      description:
          "Ensure the security of the organization's IT infrastructure.",
      skillsRequired: ["Cybersecurity", "Network Security", "Risk Management"],
      employeeReview: "Exciting work with a focus on innovation.",
    ),
    Job(
      id: "25",
      title: "Data Engineer",
      company: "DataWiz",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 80,000 - RM 110,000",
      description: "Build and maintain data pipelines.",
      skillsRequired: ["Python", "ETL", "SQL"],
      employeeReview: "Collaborative team with a focus on data innovation.",
    ),
    Job(
      id: "26",
      title: "DevOps Engineer",
      company: "DevOps Pro",
      location: "Penang, Malaysia",
      salaryRange: "RM 90,000 - RM 120,000",
      description:
          "Automate and streamline the software development lifecycle.",
      skillsRequired: ["CI/CD", "Docker", "Kubernetes"],
      employeeReview:
          "Supportive team with opportunities for skill development.",
    ),
    Job(
      id: "27",
      title: "Frontend Developer",
      company: "Web Wonders",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 70,000 - RM 100,000",
      description: "Develop and maintain user-facing features for websites.",
      skillsRequired: ["HTML", "CSS", "JavaScript"],
      employeeReview: "Creative projects with a focus on user experience.",
    ),
    Job(
      id: "28",
      title: "Game Developer",
      company: "GameOn Studios",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 80,000 - RM 110,000",
      description: "Design and develop video games.",
      skillsRequired: ["Unity", "C#", "Game Design"],
      employeeReview: "Exciting projects and a creative environment.",
    ),
    Job(
      id: "29",
      title: "IT Project Manager",
      company: "IT Solutions",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 90,000 - RM 120,000",
      description: "Manage and oversee IT projects.",
      skillsRequired: ["Project Management", "Agile", "Scrum"],
      employeeReview: "Dynamic team with a focus on project success.",
    ),
    Job(
      id: "30",
      title: "Mobile App Developer",
      company: "App Masters",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 80,000 - RM 110,000",
      description: "Develop mobile applications for iOS and Android.",
      skillsRequired: ["Flutter", "React Native", "iOS/Android Development"],
      employeeReview: "Innovative environment with exciting projects.",
    ),
    Job(
      id: "31",
      title: "Network Administrator",
      company: "Network Solutions",
      location: "Penang, Malaysia",
      salaryRange: "RM 70,000 - RM 100,000",
      description:
          "Manage and maintain the organization's network infrastructure.",
      skillsRequired: ["Networking", "Cisco", "Network Security"],
      employeeReview: "Supportive team with opportunities for growth.",
    ),
    Job(
      id: "32",
      title: "Product Manager",
      company: "Tech Innovations",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 100,000 - RM 130,000",
      description: "Oversee product development from concept to launch.",
      skillsRequired: ["Product Management", "Agile", "Market Research"],
      employeeReview: "Dynamic team with a focus on innovation.",
    ),
    Job(
      id: "33",
      title: "QA Engineer",
      company: "Quality First",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 70,000 - RM 100,000",
      description: "Ensure the quality of software products through testing.",
      skillsRequired: ["QA Testing", "Automation", "Selenium"],
      employeeReview: "Collaborative team with a focus on quality.",
    ),
    Job(
      id: "34",
      title: "Software Architect",
      company: "Architects of Code",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 120,000 - RM 150,000",
      description: "Design and oversee the implementation of software systems.",
      skillsRequired: ["Software Architecture", "Design Patterns", "Java"],
      employeeReview: "Challenging projects with a focus on innovation.",
    ),
    Job(
      id: "35",
      title: "Solutions Architect",
      company: "Solution Masters",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 110,000 - RM 140,000",
      description: "Design and implement IT solutions for clients.",
      skillsRequired: ["Cloud Computing", "AWS", "Azure"],
      employeeReview:
          "Innovative environment with a focus on client satisfaction.",
    ),
    Job(
      id: "36",
      title: "Systems Analyst",
      company: "System Solutions",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 70,000 - RM 100,000",
      description: "Analyze and improve IT systems and processes.",
      skillsRequired: ["Systems Analysis", "SQL", "Business Analysis"],
      employeeReview: "Collaborative team with a focus on efficiency.",
    ),
    Job(
      id: "37",
      title: "Technical Support Engineer",
      company: "Tech Support Co.",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 60,000 - RM 90,000",
      description: "Provide technical support for software products.",
      skillsRequired: [
        "Technical Support",
        "Customer Service",
        "Problem Solving"
      ],
      employeeReview: "Supportive environment with opportunities for growth.",
    ),
    Job(
      id: "38",
      title: "UX Researcher",
      company: "User Experience Inc.",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 70,000 - RM 100,000",
      description: "Conduct research to understand user needs and preferences.",
      skillsRequired: ["UX Research", "User Interviews", "Data Analysis"],
      employeeReview: "Creative team with a focus on user experience.",
    ),
    Job(
      id: "39",
      title: "Web Designer",
      company: "Design Masters",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 70,000 - RM 100,000",
      description: "Design and develop visually appealing websites.",
      skillsRequired: ["Web Design", "HTML", "CSS"],
      employeeReview: "Creative environment with exciting projects.",
    ),
    Job(
      id: "40",
      title: "Backend Developer",
      company: "Backend Solutions",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 80,000 - RM 110,000",
      description: "Develop and maintain server-side applications.",
      skillsRequired: ["Node.js", "Java", "SQL"],
      employeeReview:
          "Collaborative team with a focus on backend technologies.",
    ),
    Job(
      id: "41",
      title: "Big Data Engineer",
      company: "Data Giants",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 90,000 - RM 120,000",
      description: "Design and implement big data solutions.",
      skillsRequired: ["Big Data", "Hadoop", "Spark"],
      employeeReview: "Innovative projects with a focus on data.",
    ),
    Job(
      id: "42",
      title: "Cloud Engineer",
      company: "Cloud Solutions",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 90,000 - RM 120,000",
      description: "Design and manage cloud infrastructure.",
      skillsRequired: ["AWS", "Azure", "Google Cloud"],
      employeeReview:
          "Supportive team with opportunities for skill development.",
    ),
    Job(
      id: "43",
      title: "Data Visualization Specialist",
      company: "DataVis",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 80,000 - RM 110,000",
      description: "Create visual representations of data.",
      skillsRequired: ["Tableau", "Power BI", "Data Visualization"],
      employeeReview: "Collaborative environment with a focus on data.",
    ),
    Job(
      id: "44",
      title: "DevSecOps Engineer",
      company: "Secure DevOps",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 90,000 - RM 120,000",
      description: "Integrate security practices into the DevOps process.",
      skillsRequired: ["DevSecOps", "CI/CD", "Security"],
      employeeReview: "Innovative team with a focus on security.",
    ),
    Job(
      id: "45",
      title: "Full Stack Engineer",
      company: "Full Stack Masters",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 90,000 - RM 120,000",
      description: "Develop both client-side and server-side software.",
      skillsRequired: ["JavaScript", "React", "Node.js"],
      employeeReview:
          "Exciting projects with opportunities for skill advancement.",
    ),
    Job(
      id: "46",
      title: "IoT Developer",
      company: "IoT Innovations",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 80,000 - RM 110,000",
      description: "Develop and implement IoT solutions.",
      skillsRequired: ["IoT", "Embedded Systems", "C++"],
      employeeReview: "Innovative projects with a focus on IoT.",
    ),
    Job(
      id: "47",
      title: "IT Auditor",
      company: "Audit Tech",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 80,000 - RM 110,000",
      description: "Conduct IT audits to ensure compliance and security.",
      skillsRequired: ["IT Audit", "Compliance", "Risk Management"],
      employeeReview: "Collaborative team with a focus on security.",
    ),
    Job(
      id: "48",
      title: "Machine Learning Specialist",
      company: "ML Innovations",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 90,000 - RM 120,000",
      description: "Design and implement machine learning models.",
      skillsRequired: ["Machine Learning", "Python", "TensorFlow"],
      employeeReview: "Innovative projects with a focus on machine learning.",
    ),
    Job(
      id: "49",
      title: "Network Security Engineer",
      company: "Secure Networks",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 90,000 - RM 120,000",
      description: "Ensure the security of the organization's network.",
      skillsRequired: ["Network Security", "Firewall Management", "VPN"],
      employeeReview: "Exciting projects with a focus on security.",
    ),
    Job(
      id: "50",
      title: "Robotics Engineer",
      company: "RoboTech",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 90,000 - RM 120,000",
      description: "Design and develop robotic systems.",
      skillsRequired: ["Robotics", "Python", "C++"],
      employeeReview: "Innovative projects with a focus on robotics.",
    ),
  ];
}
