import 'job.dart';

List<Job> getMockJobs() {
  return [
    Job(
      id: "1",
      title: "Software Engineer",
      company: "Tech Corp",
      location: "Kuala Lumpur, Malaysia",
      salaryRange: "RM 70,000 - RM 100,000",
      description:
          "Responsible for developing and maintaining software applications.",
      skillsRequired: ["Flutter", "Dart", "Firebase"],
      employeeReview: "Innovative environment, supportive team.",
    ),
    // ... Add more mock Job instances hereJob(
    Job(
      id: "2",
      title: "Data Analyst",
      company: "Data Insights",
      location: "New York, NY",
      salaryRange: "\$70,000 - \$90,000",
      description: "Analyze data trends and provide insights.",
      skillsRequired: ["Python", "SQL", "Tableau"],
      employeeReview: "Supportive management and growth opportunities.",
    ),
    Job(
      id: "3",
      title: "Graphic Designer",
      company: "Creative Studio",
      location: "Kuala Lumpur",
      salaryRange: "RM 50,000 - RM 70,000",
      description: "Design engaging graphics for various media.",
      skillsRequired: ["Adobe Photoshop", "Illustrator", "InDesign"],
      employeeReview: "Innovative environment with creative freedom.",
    ),
    Job(
      id: "4",
      title: "Marketing Manager",
      company: "Bright Marketing",
      location: "Penang",
      salaryRange: "RM 80,000 - RM 100,000",
      description: "Lead marketing strategies and campaigns.",
      skillsRequired: ["Digital Marketing", "SEO", "Leadership"],
      employeeReview: "Dynamic team with great career progression.",
    ),
    Job(
      id: "5",
      title: "Civil Engineer",
      company: "BuildCon Engineering",
      location: "Johor Bahru",
      salaryRange: "RM 70,000 - RM 90,000",
      description: "Oversee construction projects and ensure compliance.",
      skillsRequired: ["AutoCAD", "Project Management", "Analytical Skills"],
      employeeReview: "Challenging projects with supportive colleagues.",
    ),
    Job(
      id: "6",
      title: "HR Specialist",
      company: "People First HR",
      location: "Kuala Lumpur",
      salaryRange: "RM 60,000 - RM 80,000",
      description: "Manage HR functions and employee relations.",
      skillsRequired: ["Recruiting", "HR Policies", "Communication"],
      employeeReview: "Great work culture and learning opportunities.",
    ),
    Job(
      id: "7",
      title: "IT Support Technician",
      company: "Tech Solutions",
      location: "Melaka",
      salaryRange: "RM 40,000 - RM 60,000",
      description: "Provide technical support and troubleshoot IT issues.",
      skillsRequired: ["Technical Support", "Networks", "Problem Solving"],
      employeeReview: "Supportive team with a strong focus on training.",
    ),
    Job(
      id: "8",
      title: "Business Analyst",
      company: "Insight Analytics",
      location: "Selangor",
      salaryRange: "RM 70,000 - RM 90,000",
      description: "Analyze business trends and provide strategic insights.",
      skillsRequired: ["Data Analysis", "SQL", "Business Acumen"],
      employeeReview: "Collaborative environment with growth potential.",
    ),
    Job(
      id: "9",
      title: "Restaurant Manager",
      company: "Gourmet Bistro",
      location: "Ipoh",
      salaryRange: "RM 50,000 - RM 70,000",
      description: "Manage restaurant operations and staff.",
      skillsRequired: ["Customer Service", "Management", "Food Safety"],
      employeeReview: "Fast-paced environment with a focus on quality.",
    ),
    Job(
      id: "10",
      title: "Accountant",
      company: "Prime Accounting",
      location: "Kota Kinabalu",
      salaryRange: "RM 60,000 - RM 80,000",
      description: "Manage financial records and auditing processes.",
      skillsRequired: ["Accounting", "Tax Knowledge", "Attention to Detail"],
      employeeReview: "Professional team with a focus on accuracy.",
    ),
    Job(
      id: "11",
      title: "Sales Executive",
      company: "Dynamic Sales Co.",
      location: "Kuching",
      salaryRange: "RM 45,000 - RM 65,000",
      description: "Drive sales growth and develop client relationships.",
      skillsRequired: ["Sales", "Negotiation", "Communication"],
      employeeReview: "Competitive environment with high earning potential.",
    ),
    Job(
      id: "12",
      title: "Web Developer",
      company: "Innovative Web Solutions",
      location: "Petaling Jaya",
      salaryRange: "RM 55,000 - RM 75,000",
      description: "Develop and maintain websites and web applications.",
      skillsRequired: ["HTML", "CSS", "JavaScript"],
      employeeReview:
          "Creative team and opportunities to work on diverse projects.",
    ),
  ];
}
